<div class="cHeader">
		<header>
			<div class="cLogo">
				<img class="imglogo" src="../../img/logo.png" alt="">
			</div>
			<div class="cMenu">
			<hgroup>
				<nav>
					<a href="caja.php">Caja</a>
					<a href="entrega.php">Entrega</a>
					<a href="catalogos.php">Catálogos</a>
					<a href="reportes.php">Reportes</a>
					<a href="#">Usuarios</a>
					<a href="#">Cerrar</a>
				</nav>
			</hgroup>
			</div>
		</header>
</div>